export const brand_values = ['Acer',
                            'Alienware',
                            'Apple',
                            'Asus',
                            'Awow',
                            'CTL',
                            'Dell',
                            'Gigabyte',
                            'Gizpro',
                            'HP',
                            'IView',
                            'Latitude',
                            'Lenovo',
                            'LG',
                            'LPT',
                            'Maingear',
                            'Microsoft',
                            'MSI',
                            'Panasonic',
                            'Razer',
                            'ROKC',
                            'Samsung',
                            'Shoxlab',
                            'Tocosy',
                            'Toughbook',
                            'Xammue',
                            'Xpg']

export const screen_size_values = ['15.66 Inch', 
                                    '15.6 Inch',
                                    '16 Inch', 
                                    '14 Inch', 
                                    '17.3 Inch', 
                                    '15 Inch', 
                                    '13.3 Inch', 
                                    '13.4 Inch', 
                                    '11.6 Inch',
                                    '16.2 Inch', 
                                    '13.6 Inch', 
                                    '13 Inch', 
                                    '14.5 Inch', 
                                    '12.45 Inch', 
                                    '12.2 Inch', 
                                    '17 Inch', 
                                    '13.5 Inch', 
                                    '13.1 Inch',
                                    '12 Inch', 
                                    '12.3 Inch', 
                                    '13.9 Inch', 
                                    '18 Inch', 
                                    '14.1 Inch', 
                                    '12.4 Inch', 
                                    '15.4 Inch', 
                                    '12.5 Inch', 
                                    '16.1 Inch']

export const cpu_values = [ '68000',
                            '8032',
                            'Celeron',
                            'Cortex',
                            'MediaTek',
                            'Pentium',
                            'Ryzen 3',
                            'Ryzen 5',
                            'Ryzen 7',
                            'Ryzen 9',
                            'A-series',
                            'A-series dual-core a4-3300m',
                            'AMD a series',
                            'AMD a4',
                            'AMD kabini a6-5200m quad core',
                            'AMD r series',
                            'Apple m1',
                            'Arm 7100',
                            'Athlon',
                            'Athlon silver 3050u',
                            'Atom z8350',
                            'Core 2 duo',
                            'Core 2 duo p8700',
                            'Core m3-8100y',
                            'i3',
                            'i5',
                            'i7',
                            'i9',
                            'Intel atom',
                            'Intel core 2 quad',
                            'Intel core duo',
                            'Intel core m-5y10 processor',
                            'Intel mobile cpu',
                            'Intel xeon',
                            'Others',
                            'Snapdragon']

export const ram_values = ['32 GB',
                            '8 GB',
                            '4 GB',
                            '16 GB',
                            '20 GB',
                            '12 GB',
                            '6 GB',
                            '1 GB',
                            '40 GB',
                            '2 GB',
                            '24 GB',
                            '5 GB',
                            '48 GB']

export const os_values = ['Chrome OS',
                        'Windows 10 Pro',
                        'Windows 11',
                        'Windows 11 Pro',
                        'HP thinpro',
                        'Mac os',
                        'Mac os x 10.0 cheetah',
                        'Macos 10.12 sierra',
                        'Macos 12 monterey',
                        'Microsoft windows 10 professional (64bit)',
                        'Win 11 multi-home',
                        'Windows 10',
                        'Windows 10 dg windows 7 pro 64',
                        'Windows 10 home',
                        'Windows 10 home 64',
                        'Windows 10 pro 64 bit multi-language support english/french/spanish',
                        'Windows 10 professional 64-bit',
                        'Windows 10 s',
                        'Windows 11',
                        'Windows 11 home',
                        'Windows 11 home s',
                        'Windows 11 s',
                        'Windows 7',
                        'Windows 7 home premium',
                        'Windows 7 pro + 10 pro',
                        'Windows 7 professional',
                        'Windows 8',
                        'Windows 8 pro',
                        'Windows 8.1',
                        'Windows pro']

export const grapics_values = ['',
                            'Adreno 618',
                            'Amd integrated graphics',
                            'Amd radeon',
                            'Amd radeon graphics',
                            'Amd radeon rx 540',
                            'Amd radeon rx 7600',
                            'Dedicated',
                            'Geforce gtx 1650',
                            'Geforce gtx 1650 ti',
                            'Geforce rtx 2050',
                            'Geforce rtx 3050',
                            'Geforce rtx 3050 ti',
                            'Geforce rtx 3070',
                            'Geforce rtx 3070 ti,iris xe graphics',
                            'Geforce rtx 3080',
                            'Geforce rtx 4050',
                            'Gt2 graphics',
                            'HD graphics, integrated',
                            'Integrated',
                            'Integrated amd radeon™ graphics',
                            'Integrated intel iris xe plus gpu',
                            'Integrated, dedicated',
                            'Intel arc a370m',
                            'Intel hd graphics 5000, integrated',
                            'Intel hd graphics 620, integrated',
                            'Intel iris xᵉ',
                            'Intel iris, integrated',
                            'Intel uhd graphics',
                            'Intel xe',
                            'Iris x graphics',
                            'Iris xe',
                            'Iris xe graphics',
                            'Nvidia geforce gtx 1650 4gb',
                            'Nvidia geforce mx250',
                            'Nvidia geforce mx350',
                            'Nvidia geforce mx450',
                            'Nvidia geforce mx550',
                            'Nvidia geforce rtx 2050',
                            'Nvidia geforce rtx 2070',
                            'Nvidia geforce rtx 2070 super',
                            'Nvidia geforce rtx 3050',
                            'Nvidia geforce rtx 3050 ti',
                            'Nvidia geforce rtx 3060',
                            'Nvidia geforce rtx 3070',
                            'Nvidia geforce rtx 3070 ti',
                            'Nvidia geforce rtx 3080',
                            'Nvidia geforce rtx 4050',
                            'Nvidia geforce rtx 4060',
                            'Nvidia geforce rtx 4070',
                            'Nvidia geforce rtx 4070, dedicated',
                            'Nvidia geforce rtx 4090',
                            'Nvidia geforce rtx a500',
                            'Nvidia geforce rtx2060',
                            'Nvidia quadro rtx 3000',
                            'Nvidia quadro t2000',
                            'Nvidia quadro t550',
                            'Nvidia rtx 2000 ada',
                            'Nvidia rtx 2060',
                            'Nvidia rtx 4000 ada',
                            'Nvidia rtx a1000',
                            'Nvidia rtx a2000',
                            'Nvidia rtx a3000',
                            'Nvidia rtx a4000',
                            'Nvidia rtx a5500',
                            'Nvidia rtx3070',
                            'Nvidia t1200',
                            'Qn20-m1-r',
                            'Quadro t500',
                            'Radeon 680m',
                            'Radeon 680m graphics',
                            'Radeon graphics',
                            'Rtx 2060',
                            'Rtx 2070 super',
                            'Rtx 3050',
                            'Rtx 3050 ti',
                            'Rtx 3060',
                            'Rtx 3070',
                            'Rtx 3070 ti',
                            'Rtx 3070ti',
                            'Rtx 3080 ti',
                            'Rtx 4050',
                            'Rtx 4060',
                            'Rtx 4070',
                            'Rtx 4080',
                            'Rtx a1000',
                            'Rtx a2000',
                            'Rtx a2000,uhd graphics',
                            'Rtx a3000',
                            'Rtx a500',
                            'Rtx t600',
                            'Rtx2050',
                            'Shared',
                            'T1200',
                            'T500,hd graphics, dedicated',
                            'T500,iris xe graphics',
                            'T550',
                            'UHD graphics',
                            'UHD graphics 600',
                            'UHD graphics 610']

export const graphics_coprocessor_values = ['2gb nvidia geforce mx230 graphics',
                                            'AMD athlon',
                                            'AMD athlon silver',
                                            'AMD integrated graphics',
                                            'AMD radeon',
                                            'AMD radeon 610m',
                                            'AMD radeon 680m',
                                            'AMD radeon 680m graphics',
                                            'AMD radeon 7 graphics',
                                            'AMD radeon graphics',
                                            'AMD radeon graphics 5500',
                                            'AMD radeon hd 8330',
                                            'AMD radeon hd 8790m',
                                            'AMD radeon r4',
                                            'AMD radeon r5',
                                            'AMD radeon r7',
                                            'AMD radeon rtx 3070',
                                            'AMD radeon rx 540',
                                            'AMD radeon rx vega 11',
                                            'AMD radeon vega 3',
                                            'AMD radeon vega 8',
                                            'AMD radeon vega 9',
                                            'Apple integrated graphics',
                                            'Ati mobility radeon 7500',
                                            'Dedicated',
                                            'Embedded',
                                            'Geforce rtx 2060',
                                            'HD integrated graphics',
                                            'Integrated',
                                            'Integrated amd radeon graphics',
                                            'Integrated arm mali-g52 2ee mc2 gpu',
                                            'Integrated graphics',
                                            'Integrated intel graphic',
                                            'Integrated intel graphics',
                                            'Integrated intel hd graphics',
                                            'Integrated iris xe graphics',
                                            'Integrated_graphics',
                                            'Intel',
                                            'Intel 620u',
                                            'Intel celeron',
                                            'Intel graphics integrated',
                                            'Intel graphics processor',
                                            'Intel hd',
                                            'Intel hd 4000',
                                            'Intel hd 520 graphics',
                                            'Intel hd 5500',
                                            'Intel hd graphics',
                                            'Intel hd graphics 3000',
                                            'Intel hd graphics 400',
                                            'Intel hd graphics 4000',
                                            'Intel hd graphics 4400',
                                            'Intel hd graphics 4400 integrated',
                                            'Intel hd graphics 500',
                                            'Intel hd graphics 5000',
                                            'Intel hd graphics 520',
                                            'Intel hd graphics 530',
                                            'Intel hd graphics 5300',
                                            'Intel hd graphics 5500',
                                            'Intel hd graphics 6000',
                                            'Intel hd graphics 610',
                                            'Intel hd graphics 615',
                                            'Intel hd graphics 620',
                                            'Intel hd graphics;nvidia optimus graphics',
                                            'Intel hd grpahics 500',
                                            'Intel hd integrated graphics',
                                            'Intel integrated graphics',
                                            'Intel iris',
                                            'Intel iris plus',
                                            'Intel iris xe graphics',
                                            'Intel iris xe graphics eligible integrated',
                                            'Intel uhd 620 graphics',
                                            'Intel uhd graphics',
                                            'Intel uhd graphics 520',
                                            'Intel uhd graphics 600',
                                            'Intel uhd graphics 605',
                                            'Intel uhd graphics 620',
                                            'Intel uhd graphics 630',
                                            'Intel uhd graphics premium',
                                            'Intel® iris plus graphics',
                                            'Inter core i7-8650u',
                                            'Intergrated',
                                            'M1 pro',
                                            'Mali-g72 mp3',
                                            'Mediatek',
                                            'Mediatek integrated',
                                            'Mediatek integrated graphics',
                                            'Nvidia',
                                            'Nvidia geforce',
                                            'Nvidia geforce gt 720m',
                                            'Nvidia geforce gtx 1050',
                                            'Nvidia geforce gtx 1050 ti',
                                            'Nvidia geforce gtx 1060',
                                            'Nvidia geforce gtx 1060 oc',
                                            'Nvidia geforce gtx 1070',
                                            'Nvidia geforce gtx 1070 oc with 8gb gddr5',
                                            'Nvidia geforce gtx 1650',
                                            'Nvidia geforce gtx 1660',
                                            'Nvidia geforce gtx 1660ti',
                                            'Nvidia geforce gtx 965m',
                                            'Nvidia geforce mx130',
                                            'Nvidia geforce mx150',
                                            'Nvidia geforce mx250',
                                            'Nvidia geforce mx450',
                                            'Nvidia geforce rtx',
                                            'Nvidia geforce rtx 2050',
                                            'Nvidia geforce rtx 2060',
                                            'Nvidia geforce rtx 2070',
                                            'Nvidia geforce rtx 2070 max-q',
                                            'Nvidia geforce rtx 2080',
                                            'Nvidia geforce rtx 2080 8gb gddr6',
                                            'Nvidia geforce rtx 2080 max-q',
                                            'Nvidia geforce rtx 2080 super',
                                            'Nvidia geforce rtx 3050',
                                            'Nvidia geforce rtx 3050 ti',
                                            'Nvidia geforce rtx 3050 ti max-q graphics',
                                            'Nvidia geforce rtx 3060',
                                            'Nvidia geforce rtx 3070',
                                            'Nvidia geforce rtx 3070 ti',
                                            'Nvidia geforce rtx 3070 ti 8gb gddr6',
                                            'Nvidia geforce rtx 3080',
                                            'Nvidia geforce rtx 3080 laptop gpu',
                                            'Nvidia geforce rtx 3080 ti',
                                            'Nvidia geforce rtx 4050',
                                            'Nvidia geforce rtx 4060',
                                            'Nvidia geforce rtx 4070',
                                            'Nvidia geforce rtx 4080',
                                            'Nvidia geforce rtx 4090',
                                            'Nvidia geforce trx 3070',
                                            'Nvidia intel geforce rtx 3070 ti iris xe graphics',
                                            'Nvidia intel rtx a2000 uhd graphics',
                                            'Nvidia intel t500 iris xe graphics',
                                            'Nvidia quadro 3050 6gb gddr6',
                                            'Nvidia quadro k1100m',
                                            'Nvidia quadro p1000',
                                            'Nvidia quadro rtx 3000',
                                            'Nvidia quadro t1000',
                                            'Nvidia quadro t1200',
                                            'Nvidia quadro t2000',
                                            'Nvidia rtx 2070',
                                            'Nvidia rtx 2080 super',
                                            'Nvidia rtx 3000 6gb gddr6',
                                            'Nvidia rtx 3050ti',
                                            'Nvidia rtx 5000 16gb gddr6',
                                            'Nvidia rtx a1000',
                                            'Nvidia rtx a2000',
                                            'Nvidia rtx a2000 w/4gb',
                                            'Nvidia rtx a3000',
                                            'Nvidia rtx a3000 12gb gddr6',
                                            'Nvidia rtx a3000 16gb gddr6',
                                            'Nvidia rtx a4000 8gb gddr6',
                                            'Nvidia rtx a4500',
                                            'Nvidia rtx a500',
                                            'Nvidia rtx a5500 16gb gddr6',
                                            'Nvidia t550',
                                            'Nvidia t600',
                                            'Nvidia ® geforce rtx™ 2060',
                                            'Nvidia ® geforce rtx™ 4050',
                                            'Powervr gx6250',
                                            'Quadro p1000',
                                            'Radeon pro wx vega m gl',
                                            'UHD graphics',
                                            'UHD graphics 600',
                                            'Xps9300-7909slv-pus']

export const harddisk_values = ['512 GB',
                                '128 GB',
                                '64 GB',
                                '1024 GB',
                                '1000 GB',
                                '256 GB',
                                '32 GB',
                                '16 GB',
                                '240 GB',
                                '120 GB',
                                '300 GB',
                                '2000 GB',
                                '480 GB',
                                '500 GB',
                                '320 GB',
                                '250 GB',
                                '160 GB',
                                '8 GB',
                                '1256 GB']

export const special_features_values = ['Memory card slot',
                                        'HD audio',
                                        'Numeric keypad',
                                        'Fingerprint reader',
                                        'Backlit keyboard',
                                        'Anti glare coating',
                                        'Ultra-slim bezel',
                                        'Dolby',
                                        'Support stylus',
                                        'Support pen',
                                        '144hz refresh rate',
                                        'Touchscreen']                                